FROM node:20-alpine

# Diretório de trabalho
WORKDIR /app

# Copia apenas arquivos necessários para instalar dependências
COPY package*.json ./

# Instala as dependências
RUN npm install --production

# Copia o restante dos arquivos
COPY . .

# Expõe a porta da aplicação
EXPOSE 8000

# Comando padrão
CMD ["node", "index.js"]
